### ISSUE TITLE
Does this code run on linux?

### ISSUE THREAD

**Issue by Weyaaron** [ShootMe/LiveSplit.Celeste#7]
I would like to speedrun Celeste on linux, and running this code would improve my trainig-possibilities.  I'm new to c#-development, but since I study computerscience, I have decent knowledge of programming in general.

**Comment by ShootMe** [comment]
LiveSplit and the plugins associated with it (autospllitters) use code specific to Windows (pinvokes) to read memory. So it will not run on Linux. The code also would probably have to change since the memory layout would most likely be slightly different than on Windows. I know some other people have looked into things like this on Linux/Mac but I do not have any experience or info about it.
